"""Centralized vendor alias map.

Used by both the real-time processor (sync_now) and batch rematch script.
Maps lowercase alias -> canonical vendor name.
"""

VENDOR_ALIASES: dict[str, str] = {
    # From WeChat OneDrive folder names
    "kaito": "Kaito",
    "haisan": "Haisan",
    "eva surf": "EVA Surf Products",
    "zhixing": "Zhixing Educational Toys",
    "perflex": "Changsha Perflex",
    "kihome": "Qihao Home Kihome",
    "qihao": "Qihao Home Kihome",
    "avant sports": "Avant Sports",
    "waytop": "Qingdao Waytop",
    "colin hpl": "Colin HPL",
    "bingyao": "Hebei BingYao",
    "laikeman": "Laikeman",
    "courtyard garden": "Courtyard Garden",
    "siki": "SIKI Lighting",
    "moonhill": "Moonhill",
    "you le jia": "YOU LE JIA",
    "guocio": "Aqara",
    "jingying": "Jingying Lighting",
    "kaiyuan": "KAIYUAN Lighting",
    "mason": "MASON Strip Light",
    "nanolux": "NANOLUX",
    "zm sculpture": "ZM Sculpture",
    "flyon": "Flyon Sport",
    "shangdong century": "Shangdong Century Sports",
    # Chinese vendor names from filenames
    "洪馨": "Hongxin",
    "庭院故事": "Courtyard Garden",
    "华富立": "Huafuli",
    "京图": "Jingtu",
    "追美": "Zhuimei",
    "将力": "Jiangli",
    "曼尼特": "Manitta",
    "佛洛伦克": "Florenk",
    "环星": "Huanxing",
    "必美": "Bimei",
    "博生": "Bosheng",
    "诗韵": "Shiyun",
    "美尚": "Meishang",
    "非常面子": "FOSB",
    "浪潮": "Langchao",
    "卫域": "Weiyu",
    "鸿政威": "Hongzhengwei",
    "捷觅": "Jiemi Lighting",
    "栢格": "Baige",
    "莱珂曼": "Laikeman",
    "永正大": "Yongzhengda",
    "月亮山": "Moonhill",
    "广州月亮山": "Moonhill",
    # Discovered from PDF content scanning
    "anhui aolo": "Anhui Aolo New Materials",
    "aolo": "Anhui Aolo New Materials",
    "topflor": "Topflor Plastics Nantong",
    "kmina": "Shenzhen Kmina New Material",
    "century star": "Century Star Sports",
    "leopor": "Jiangsu Leopor New Material",
    "taicheng": "Linhai Taicheng Artware",
    "ocreation": "Ocreation International Trade",
    "huashen": "Guangdong Huashen Industrial",
    "warrior": "Warrior Outbound Equipment",
    "uogel": "Uogel Decoration Material",
    "durasein": "Durasein",
    "ccns": "CCNS Engineered Wood",
    "koon studio": "Koon Studio",
    "tumaco": "Tumaco",
    "fly world": "Fly World Logistics",
    "hzw": "Guangzhou HZW Commercial",
    "nets tribe": "Nets Tribe",
    "cowboy": "Cowboy Group",
    "berson": "Berson Furniture",
    "kapok": "Kapok",
    "camerich": "Camerich",
    "tutti": "TUTTI Hardware",
    "suphia": "Suphia Furniture",
    "metrube": "Metrube",
    "hooz": "Hooz Furniture",
    "ubess": "Ubess Wooden Texture",
    "upin": "Upin Colors",
    "goldenbreeze": "Goldenbreeze",
    "nature green": "Nature Green Floors",
    "mingsu": "Mingsu Umbrellas",
    "chao li": "Chao Li Webbing",
    "dk jute": "DK Jute",
    "davang": "DaWang Fans",
    "dawang": "DaWang Fans",
    "steamline": "Steamline Panel",
    "pelucchi": "Pelucchi Ventilation",
    "leawod": "Leawod Doors",
    "water house": "Water House",
    "basten": "Basten",
    "wisdom": "Wisdom",
    "jrace": "Jrace",
    "sofa webbing": "Sofa Webbing",
    "hongxin": "Hongxin",
    "rive gauche": "Connoiseur RIVE GAUCHE",
}
